apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-mysql-pv-claim
  labels:
    app: seafile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.storageDb}}G
