apiVersion: v1
kind: Service
metadata:
  name: seafile
  labels:
    app: seafile
spec:
  ports:
    - port: {{ int .Values.port}}
      targetPort: 80
  selector:
    app: seafile
    tier: frontend
  type: LoadBalancer