apiVersion: v1
kind: Service
metadata:
  name: seafile
  labels:
    app: seafile
spec:
  ports:
{{/*    - port: 30088*/}}
{{/*      targetPort: 80*/}}
    - port: {{ int .Values.port}}
    {{- if .Values.ssl.enabled }}
      targetPort: 443
    {{- else }}
      targetPort: 80
    {{- end }}
  selector:
    app: seafile
    tier: frontend
  type: LoadBalancer