apiVersion: v1
kind: Service
metadata:
  name: seafile
  labels:
    app: seafile
spec:
  ports:
    - port: {{ int .Values.port}}
      targetPort: 80
      name: http
    {{- if .Values.exportInternalPort.enabled}}
    - port: {{.Values.exportInternalPort.seafileMain}}
      targetPort: 8000
      name: seafile
    - port: {{.Values.exportInternalPort.seafileSeafdav}}
      targetPort: 8080
      name: seafdav
    - port: {{.Values.exportInternalPort.seafileSeafhttp}}
      targetPort: 8082
      name: seafhttp
    {{- end }}
  selector:
    app: seafile
    tier: frontend
  type: LoadBalancer