apiVersion: v1
kind: Secret
metadata:
  name: seafile-pass
type: Opaque
data:
  dbRootPassword: {{ .Values.dbRootPassword | b64enc | quote }}
  adminPassword: {{ .Values.adminPassword | b64enc | quote }}